### ISSUE TITLE
Document how to install the package

### ISSUE THREAD

**Issue by pallix** [archaeron/purescript-yaml#3]
Hi there,

It would be nice to add documentation on how to install this module. Doing `bower install purescript-yaml` results in a password to be prompted.

```

bower install purescript-yaml --save
bower purescript-yaml#*     not-cached https://github.com/CapillarySoftware/purescript-yaml.git#*
bower purescript-yaml#*        resolve https://github.com/CapillarySoftware/purescript-yaml.git#*
Username for 'https://github.com': ^C
```

Apparently another `purescript-yaml` exists but I cannot find its source on GitHub.

I found that doing `bower install archaeron/purescript-yaml ` is the solution to install the version of this repository.

**Comment by dgendill** [comment]
I've added some documentation on my fork [dgendill/purescript-yaml](https://github.com/dgendill/purescript-yaml).
